### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by Juarezdoposto** [LenShustek/arduino-playtune#11]
I was searching for how the gameboy sounds work and I realized that both of the data have interrupt routines and note information, could this type of data be played directly from the playtune instead of converting to the bytestream ? `FC 33 2F F6 C0 05 28 E3 BC 05 26 D2 D0 05 26 B2 E0 05 26 C2 F0 05 28 B1 00 06 FF FC 99 2E C6 B1 04 27 C3 AD 04 25 B2 C1 04 28 92 D1 04 26 A2 E1 04 28 91 F1 04 FF 2A E6 5C 2A D6 6C 24 C2 4C 26 D3 5C 28 B3 4C 28 A1 5C FF`

**Comment by LenShustek** [comment]
I'm afraid I can't answer your question in detail because I don't know how Gameboy encodes sound information.  I don't recognize anything in the hex you provided. In any case it  won't work as input to Playtune instead of the playtune-defined bytestream.
Here are some resources I found about Gameboy sound formats that might be helpful:
 https://en.wikipedia.org/wiki/Game_Boy_Sound_System
 https://ocremix.org/info/GBS_Format_Specification

**Comment by Juarezdoposto** [comment]
Very Thank You,I gonna spend sometime researching on this links so
