### ISSUE TITLE
Delays are slightly off when playing files on the nano

### ISSUE THREAD

**Issue by joeybab3** [LenShustek/arduino-playtune#7]
I opened this as an issue on miditones on accident, so i closed and reopened here, now this time i have a little bit better of examples to go with it:
[https://www.youtube.com/watch?v=mjfMvfOdT84](https://www.youtube.com/watch?v=mjfMvfOdT84)
[MIDI and .C Files](https://github.com/LenShustek/arduino-playtune/files/416391/WF_TIMEMACHINE_5.zip)

**Comment by joeybab3** [comment]
I just tested this on an uno, and a mega and the issue persists, the same strange delays on the same notes. 
EDIT: This file works fine on the older(2013) version of the library from google code:
[https://www.youtube.com/watch?v=LG6vDmhzuRA](https://www.youtube.com/watch?v=LG6vDmhzuRA)

**Comment by LenShustek** [comment]
Aha -- thank you for trying the 2013 version and seeing that it works there!
I suspect that the timing errors are an unintended consequence of  the change T Wasiluk's submitted in May 2016 to support the ATmega32U4 processor on the Micro and Leonardo Arduino boards. He changed the timer used for score timing from an 8-bit timer (#2) to a 16-bit timer (#1), because the 32U4 doesn't have timer #2. I haven't yet figured out why that causes a problem, but I'll keep looking at it and running tests.

**Comment by LenShustek** [comment]
Found it! The change to a 16-bit timer for score waits exposed an old bug that was in the original Brett Hagman code: when writing the timer OCR value (what it compares the counter to), we need to clear the counter, or else (the manual says) "the counter [might] miss the compare match...and will have to count to its maximum value (0xFFFF) and wrap around starting at 0 before the compare match can occur". This caused an error that was short and not noticeable for the 8-bit timer, but could be hundreds of milliseconds for the 16-bit counter. 

It will take me a little while to publish new code because I have other changes I want to make, but you can try out the fix by adding "TCNT1 = 0;" after the statement "OCR1A = ocr;" in Playtune.cpp.  Let me know if it works for you.

**Comment by LenShustek** [comment]
Ok, I just uploaded a new version with all my changes. Thanks for your help in finding the timing bug!

**Comment by joeybab3** [comment]
Any time! I can't wait to try it out, Im glad to have helped!
